version: '4'

services:
    backend:
        build:
            context: .
        ports:
            - 5000:5000
        env_file:
            - .env
        depends_on:
            - mongo
    mongo:
        image: mongo:latest
        ports:
            - 27017:27017
        volumes:
            - db1:/data/db
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example

volumes:
    db1:
