version: '4'

services:
    backend:
        build: .
        ports:
            - 5000:5000
        env_file:
            - .env
        depends_on:
            - mongo
            - redis
        networks:
            ohyeah:
                ipv4_address: '10.56.1.21'
    mongo:
        image: mongo:latest
        ports:
            - 27017:27017
        volumes:
            - db:/data/db
        networks:
            ohyeah:
                ipv4_address: '10.56.1.20'
    redis:
        image: redis:latest
        ports:
            - 6379:6379
        networks:
            ohyeah:
                ipv4_address: '10.56.1.19'

volumes:
    db:

networks:
    ohyeah:
        ipam:
            driver: default
            config:
                - subnet: '10.56.1.0/24'
