name: Instahost CI CD

on:
    push:
        branches: ['main']

jobs:
    build:
        runs-on: self-hosted

        strategy:
            matrix:
                node-version: [20.x]

        env:
            PORT: 3000
            NODE_ENV: production
            PROTOCOL: http
            HOST: localhost
            BASE_URL: http://localhost:3000
            CLIENT_URL: http://localhost:3001
            MONGODB_URI: ${{ secrets.MONGODB_URI }}
            JWT_SECRET: ${{ secrets.JWT_SECRET }}
            SMTP_USER: ${{ secrets.SMTP_USER }}
            SMTP_PASS: ${{ secrets.SMTP_PASS }}
            COOKIE_SECRET: ${{ secrets.COOKIE_SECRET }}
            AWS_REGION: ${{ secrets.AWS_REGION }}
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_S3_BUCKET_NAME: ${{ secrets.AWS_S3_BUCKET_NAME }}
            AWS_S3_BUCKET_BASE_URL: ${{ secrets.AWS_S3_BUCKET_BASE_URL }}
            GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
            GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}

        steps:
            - uses: actions/checkout@v4

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'npm'

            - name: Install client dependencies
              working-directory: ./client
              run: npm install

            - name: Build client
              working-directory: ./client
              run: npm run build

            - name: Install server dependencies
              run: npm install

            - name: Build server
              run: npm run build

            - name: Restart pm2
              run: pm2 reload ecosystem.config.json --update-env
