name: Instahost CI CD

on:
    push:
        branches: ['main']

jobs:
    build:
        runs-on: self-hosted

        strategy:
            matrix:
                node-version: [20.x]

        env:
            PORT: 5000
            NODE_ENV: production
            PROTOCOL: https
            HOST: alokskj.tech
            BASE_URL: https://alokskj.tech
            CLIENT_URL: http://alokskj.tech
            PLATFORM_CNAME: cname.alokskj.tech
            MONGODB_URI: ${{ secrets.MONGODB_URI }}
            JWT_SECRET: ${{ secrets.JWT_SECRET }}
            SMTP_USER: ${{ secrets.SMTP_USER }}
            SMTP_PASS: ${{ secrets.SMTP_PASS }}
            COOKIE_SECRET: ${{ secrets.COOKIE_SECRET }}
            AWS_REGION: ${{ secrets.AWS_REGION }}
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_S3_BUCKET_NAME: ${{ secrets.AWS_S3_BUCKET_NAME }}
            AWS_S3_BUCKET_BASE_URL: ${{ secrets.AWS_S3_BUCKET_BASE_URL }}
            GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
            GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}

        steps:
            - uses: actions/checkout@v4

            - name: Install client dependencies
              working-directory: ./client
              run: npm ci --production=false

            - name: Build client
              working-directory: ./client
              run: npm run build

            - name: Install server dependencies
              run: npm ci --production=false

            - name: Build server
              run: npm run build

            - name: Restart pm2
              run: pm2 reload ecosystem.config.json --update-env && pm2 reset instahost && pm2 save
