name: CI CD

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Login to docker hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    - name: Build the Docker image
      run: docker build . --file Dockerfile -t alokskj/instahost
    - name: Publish image to docker hub
      run: docker push alokskj/instahost:latest

  deploy:

      needs: build
      runs-on: self-hosted
      steps:
      - name: Pull image from docker hub
        run: docker pull alokskj/instahost:latest
      - name: Delete old container
        run: docker rm -f instahost
      - name: Print current path
        run: pwd
      - name: Run docker container
        run: docker run -d -p --env-file ./.env 5000:5000 --name instahost alokskj/instahost

   